# References https://gist.github.com/dan-blanchard/7045057
# and https://docs.travis-ci.com/user/trusty-ci-environment/

sudo: false
dist: trusty

branches:
  only:
    - master

matrix:
  include:
    - env: PYTHON=2.7
    - env: PYTHON=3.4

before_install:

  # Install Miniconda
  - wget -q https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p ~/anaconda
  - export PATH=~/anaconda/bin:$PATH

  - SRC_DIR=$(pwd)

  # Setup environment
  - conda update --yes conda
  - conda create -n travisci --yes python=$PYTHON pip
  - source activate travisci
  - CONDA_INSTALL="conda install --yes -q"
  - PIP_INSTALL="pip install -q"

  # Install ecpy dependencies
  - $CONDA_INSTALL pyqt future numpy
  - $PIP_INSTALL configobj watchdog

  # Install enaml/atom/kiwisolver from sources as we need the latest bug fixes and Py2/3 compat
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/kiwi/tarball/py3
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/atom/tarball/py23
  - $PIP_INSTALL https://github.com/MatthieuDartiailh/enaml/tarball/parser23

  # Intall test tools
  - $CONDA_INSTALL pytest
  - $PIP_INSTALL pytest-cov pytest-capturelog pytest-timeout

  # Install codecov report tools
  - $PIP_INSTALL codecov

install:

    # Install ecpy (check that build script is not broken
    - cd ${SRC_DIR}
    - python setup.py install
    - cd ~

before_script:
# I need a (fake) display on Travis so I need to start a X server.
- export DISPLAY=:99.0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render

script:
    # Run the Ecpy test suite
    - cd ${SRC_DIR}
    - py.test tests --cov ecpy --cov-report xml

after_success:
    - cd ${SRC_DIR}
    - codecov
