package:
  name: ecpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') +
             ( '' if environ.get('GIT_DESCRIBE_NUMBER', '0')  == '0' else
              ('.post' + environ.get('GIT_DESCRIBE_NUMBER', '0' )
               )
              )}}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - ecpy = ecpy.__main__:main
  osx_is_app: True

requirements:
  build:
    - python
    - future
  run:
    - python
    - python.app       [osx]
    - enaml >=0.10.2
    - pyqt
    - atom >=0.4.1
    - kiwisolver >=1.0.0
    - future
    - watchdog
    - configobj
    - qtawesome
    - numpy

test:
  commands:
    - ecpy --help
  imports:
    - ecpy

app:
  entry: ecpy
  summary: 'Ecpy application'

about:
  home: https://github.com/Ecpy/ecpy
  license: BSD
  license_file: LICENSE
  summary: High level experiment automation program
