package:
  name: ecpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../
  git_tag: master

build:
  noarch_python: True
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - ecpy = ecpy.__main__:main
  osx_is_app: True
  track_features:
    - enaml-python3

requirements:
  build:
    - python
    - future
  run:
    - python
    - python.app       [osx]
    - enaml >=0.9.9
    - atom >=0.3.11
    - pyqt
    - kiwisolver >0.1.3
    - ply
    - future
    - watchdog
    - configobj

test:
  commands:
    - ecpy --help
  imports:
    - ecpy

app:
  entry: ecpy
  summary: 'Ecpy application'

about:
  home: https://github.com/Ecpy/ecpy
  license: BSD
  license_file: LICENSE
  summary: High level experiment automation program
