package:
  name: ecpy
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/Ecpy/ecpy.git
  git_tag: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 1) }}
  entry_points:
    - ecpy = ecpy.__main__:main
  osx_is_app: True

requirements:
  build:
    - python
    - future
  run:
    - python
    - python.app       [osx]
    - enaml >0.9.8
    - atom >0.3.10
    - kiwisolver >0.1.3
    - future
    - watchdog
    - configobj
    - qtawesome
    - numpy

test:
  commands:
    - ecpy --help
  imports:
    - ecpy

app:
  entry: ecpy
  summary: 'Ecpy application'

about:
  home: https://github.com/Ecpy/ecpy
  license: BSD
  license_file: LICENSE
  summary: High level experiment automation program
